In [1]:
import numpy as np

### 독립변수 x 생성

In [3]:
x = np.random.uniform(low = 0.0, high = 1.0, size = 100) # 0~~1사이 100개의 랜덤 값 생성
print(x.shape)
x[:3] #데이터 3개만 출력

(100,)


array([0.91578665, 0.00127379, 0.43580379])

### 종속변수 y = wx + b 생성

In [4]:
'''w = 10, b = 2'''
y = 10*x + 2
print(y.shape)
y[:3]

(100,)


array([11.15786649,  2.01273786,  6.35803785])

In [54]:
w = np.random.uniform(low=0.0, high=1.0)
b = np.random.uniform(low=0.0, high=1.0)

learning_rate = 3.083
num_epoch = 300

w,b

(0.8604510225060181, 0.0759402705869554)

In [55]:
for epoch in range(num_epoch) : ##몇번학습??
    print(f"{epoch:2}, w = {w:.4f}, b = {b:.4f}")
    
    """랜덤설정된 w,b값의 결과"""
    y_pre = w * x + b
    
    """MSE(평균제곱오차)"""
    mse = ((y_pre - y)**2).mean()
    print(mse)
    
    error = np.abs(y_pre - y).mean()
    if error < 0.001 :
        break
       
    ##(wx+b - y)**2 >> 2(wx+b-y)x : 미분
    
    w = w - learning_rate*((y_pre - y)*x).mean()
    b = b - (y_pre - y).mean()
    ## w = w - ((a * dw/d) * cost(w))    : cost(w) == (wx+b-y)**2
 
print("-"*50)
print(f"{epoch:2}, w = {w:.4f}, b = {b:.4f}")

 0, w = 0.8605, b = 0.0759
45.83673453707871
 1, w = 12.2902, b = 6.2884
29.216929134034334
 2, w = 3.9199, b = 0.9254
18.62991279574692
 3, w = 11.2265, b = 4.8529
11.884012980612717
 4, w = 5.9392, b = 1.4245
7.58428644738619
 5, w = 10.6134, b = 3.9054
4.842747150941568
 6, w = 7.2768, b = 1.7122
3.0940236195555912
 7, w = 10.2694, b = 3.2778
1.9780761000473421
 8, w = 8.1661, b = 1.8736
1.2655708702942756
 9, w = 10.0839, b = 2.8605
0.8103911953158931
10, w = 8.7597, b = 1.9606
0.5194129869075875
11, w = 9.9901, b = 2.5820
0.333265622923953
12, w = 9.1576, b = 2.0047
0.2140831979876023
13, w = 9.9478, b = 2.3953
0.13770473810330316
14, w = 9.4254, b = 2.0245
0.08870632206591629
15, w = 9.9336, b = 2.2696
0.05723610907385741
16, w = 9.6064, b = 2.0312
0.03699739187638155
17, w = 9.9337, b = 2.1847
0.0239628322308018
18, w = 9.7293, b = 2.0311
0.015554506042628176
19, w = 9.9404, b = 2.1270
0.010120783263599116
20, w = 9.8130, b = 2.0280
0.006602425160073068
21, w = 9.9494, b = 2.087

In [9]:
print("%.2f"%(2.123456789)) ##.2f 소수점 2자리까지

2.12


### 독립 변수 2개 생성

In [56]:
x1 = np.random.uniform(low= 0.0 , high = 1.0, size = 100)
x2 = np.random.uniform(low= 0.0 , high = 1.0, size = 100)

y2 = 3*x1 + 7*x2 + 10  ## w1 = 3, w2 = 7, b = 10
print(y2.shape)
print(x1[:2])
print(x2[:2])
print(y2[:2])

(100,)
[0.78241698 0.94229871]
[0.58224214 0.03821385]
[16.42294593 13.0943931 ]


In [101]:
w1 = np.random.uniform(low= 0.0 , high = 1.0)
w2 = np.random.uniform(low= 0.0 , high = 1.0)
b = np.random.uniform(low= 0.0 , high = 1.0)
## learning rate와 epoch 설정 해주기
learning_rate = 1.33
num_epoch = 200

w1, w2, b

(0.11650307962351647, 0.6585966285179502, 0.6329413272055856)

In [102]:
for epoch in range(num_epoch) :
    print(f"{epoch:2}, w1 = {w1:.4f}, w2 = {w2:.4f}, b = {b:.4f}")
    
    y2_pre = w1*x1 + w2*x2 + b
    mse = ((y2_pre - y2)**2).mean()
    print(mse)
    
    error = np.abs(y2_pre - y2).mean()
    
    if error < 0.001 :
        break
    
    w1 = w1 - learning_rate*((y2_pre - y2)*x1).mean()
    w2 = w2 - learning_rate*((y2_pre - y2)*x2).mean()
    b = b - (y2_pre - y2).mean()
print('-'*50)
print(f"{epoch:2}, w1 = {w1:.4f}, w2 = {w2:.4f}, b = {b:.4f}")    

 0, w1 = 0.1165, w2 = 0.6586, b = 0.6329
190.7688477991887
 1, w1 = 8.9837, w2 = 9.7940, b = 14.2965
74.1478336528519
 2, w1 = 3.1063, w2 = 4.2574, b = 5.9002
28.93916341924749
 3, w1 = 6.4360, w2 = 7.8344, b = 11.2245
11.393937791298454
 4, w1 = 4.0647, w2 = 5.7249, b = 8.0035
4.568232664301749
 5, w1 = 5.2673, w2 = 7.1407, b = 10.0939
1.8990996585454427
 6, w1 = 4.2696, w2 = 6.3507, b = 8.8730
0.844013363551369
 7, w1 = 4.6628, w2 = 6.9227, b = 9.7072
0.41759072715855183
 8, w1 = 4.2102, w2 = 6.6375, b = 9.2574
0.23761056867000918
 9, w1 = 4.3020, w2 = 6.8773, b = 9.6018
0.15554367196936755
10, w1 = 4.0714, w2 = 6.7828, b = 9.4474
0.11344990591542314
11, w1 = 4.0564, w2 = 6.8896, b = 9.5993
0.08854362761059481
12, w1 = 3.9209, w2 = 6.8652, b = 9.5567
0.07171300994166276
13, w1 = 3.8728, w2 = 6.9171, b = 9.6315
0.05919089045264034
14, w1 = 3.7816, w2 = 6.9168, b = 9.6299
0.049320616812657626
15, w1 = 3.7277, w2 = 6.9448, b = 9.6727
0.04129652237610392
16, w1 = 3.6600, w2 = 6.9515, b =

In [103]:
import pandas as pd

In [108]:
x_train = pd.DataFrame([x1,x2], index=["x1", "x2"])
x_train = x_train.T
x_train.head()

x1        x2
0  0.782417  0.582242
1  0.942299  0.038214
2  0.111165  0.007734
3  0.677183  0.003942
4  0.349401  0.505361

In [110]:
y_train = pd.Series(y2)
print(y_train.shape)
y_train.head()

(100,)


0    16.422946
1    13.094393
2    10.387632
3    12.059141
4    14.585730
dtype: float64

In [111]:
from sklearn.linear_model import LinearRegression ##선형회귀모델

In [112]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [113]:
model.score(x_train,y_train)

1.0

In [114]:
print(model.coef_)
print(model.intercept_)

[3. 7.]
9.999999999999998


In [ ]:
### y = w1x1 + w2x2 + b

### y = model.coef_[0]*x1 + model.coef_[1]]*x2 + model.intercept_

### y = 3x1 + 7x2 + 10 


In [115]:
model.predict([[2,5]])

array([51.])