In [273]:
import pandas as pd
import numpy as np

In [274]:
mydata = pd.read_excel('./data/mydata.xlsx')
mydata.head()

user_id  media_id preference job gender  age  rate
0        1         1         요리  학생      여   20    10
1        1         2         요리  학생      여   20     9
2        1         3         요리  학생      여   20     9
3        1         4         요리  학생      여   20     8
4        1         5         요리  학생      여   20     9

In [275]:
data =pd.read_excel('./data/통합본db용2.xlsx', index_col = '번호')

In [276]:
data = data.sort_index()

In [277]:
data.index

Int64Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
            18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
            35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
            52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
            68],
           dtype='int64', name='번호')

In [278]:
data['카테고리'].unique()

array(['요리, 간단요리', '요리,간단', '요리,팁', '요리,길거리', '요리, 길거리', '교육_영어회화',
       '영화_예고편', '영화_리뷰', '음악,kpop', '동물_고양이', '동물_강아지', '음악_외국음악', '어학',
       '애니메이션,만화'], dtype=object)

In [279]:
data['카테고리'] =data['카테고리'].apply(lambda x : x.replace('_',','))

In [280]:
#data['카테고리'] = data['카테고리'].apply(lambda x : x.split(','))

In [281]:
data['카테고리']

번호
1     요리, 간단요리
2        요리,간단
3         요리,팁
4        요리,간단
5        요리,간단
        ...   
64    애니메이션,만화
65    애니메이션,만화
66    애니메이션,만화
67    애니메이션,만화
68    애니메이션,만화
Name: 카테고리, Length: 68, dtype: object

In [282]:
data['재생시간']

번호
1     10,02 
2      2,09 
3      3,43 
4      5,07 
5      2,11 
       ...  
64      2,00
65     3,21 
66     3,41 
67    10,24 
68     4,31 
Name: 재생시간, Length: 68, dtype: object

In [283]:
data['재생시간'] = data['재생시간'].apply(lambda x : x.strip())
data['재생시간'].head()

번호
1    10,02
2     2,09
3     3,43
4     5,07
5     2,11
Name: 재생시간, dtype: object

In [284]:
data['재생시간'] = data['재생시간'].apply(lambda x : x.split(','))

In [285]:
data['재생시간']

번호
1     [10, 02]
2      [2, 09]
3      [3, 43]
4      [5, 07]
5      [2, 11]
        ...   
64     [2, 00]
65     [3, 21]
66     [3, 41]
67    [10, 24]
68     [4, 31]
Name: 재생시간, Length: 68, dtype: object

In [286]:
len(data)

68

In [287]:
for i in range(1,len(data)+1) :
    try :
        data['재생시간'][i] = int(data['재생시간'][i][0])*60 + int(data['재생시간'][i][1])
        print(data['재생시간'][i])
    except : 
        data['재생시간'][i] = int(data['재생시간'][i][0])*60
        print(data['재생시간'][i])

602
129
223
307
131
764
162
133
593
253
181
328
64
68
134
203
247
310
619
60
144
185
217
324
609
76
142
203
257
325
611
182
230
315
118
779
600
60
135
208
213
289
601
779
128
175
237
313
605
759
119
193
260
297
602
72
149
229
287
778
570
264
90
120
201
221
624
271


C:\Users\SMT002\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\SMT002\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [288]:
data['재생시간']

번호
1     602
2     129
3     223
4     307
5     131
     ... 
64    120
65    201
66    221
67    624
68    271
Name: 재생시간, Length: 68, dtype: object

In [289]:
data = data[['제목','카테고리','재생시간','조회수']]

In [290]:
from sklearn.feature_extraction.text import CountVectorizer

In [291]:
count_vector = CountVectorizer()

In [292]:
data['카테고리'][1]

'요리, 간단요리'

In [293]:
c_vec_cat = count_vector.fit_transform(data['카테고리'])

In [294]:
print(c_vec_cat.toarray())

[[0 0 1 ... 0 1 0]
 [0 1 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [295]:
print(count_vector.get_feature_names())

['kpop', '간단', '간단요리', '강아지', '고양이', '교육', '길거리', '동물', '리뷰', '만화', '애니메이션', '어학', '영어회화', '영화', '예고편', '외국음악', '요리', '음악']


In [296]:
from sklearn.metrics.pairwise import cosine_similarity

In [297]:
cos_sim = cosine_similarity(c_vec_cat, c_vec_cat).argsort()[:,::-1]

In [298]:
print(cos_sim)

[[ 0  2  7 ... 37 36 33]
 [ 1  3  4 ... 37 36 33]
 [ 2  0  7 ... 37 36 33]
 ...
 [67 65 64 ... 35 34  0]
 [67 65 64 ... 35 34  0]
 [67 65 64 ... 35 34  0]]


In [299]:
cos_sim.shape

(68, 68)

In [300]:
def get_recommend_media(df, title, top=5) :
    target_media_index = df[df['제목']==title].index.values
    
    simm_index = cos_sim[target_media_index,:top].reshape(-1)
    
    simm_index = simm_index[simm_index != target_media_index]
    
    result = df.iloc[simm_index].sort_values('조회수',ascending = False)[:10]
    
    return result

In [301]:
data[data['제목']=='세상 간단한 라면 요리 10가지'].index.values

array([1], dtype=int64)

In [390]:
movies = get_recommend_media(data, title='[조커] 메인 예고편')

In [391]:
m_index = movies.index

In [393]:
movies['id'] = m_index

In [396]:
movies['cat'] = 2
movies['user_id'] = 'dptmf35'

In [398]:
movies[['id','cat','user_id']].to_excel('movies.xlsx')

In [389]:
get_recommend_media(data, title='세상 간단한 라면 요리 10가지')

제목   카테고리 재생시간       조회수
번호                                                             
4                           닭껍질 튀김+뿌링클 가루  요리,간단  307  10483825
7   전자렌지 3분 완성 마약토스트, 중독성 강한 식빵 요리 by 은수저  요리,간단  162   1696499
5                   [BIBIMBAP] 고추장 계란 비빔밥  요리,간단  131   1207660
6           1분 시리얼 토스트 ! 1분이면 끝! [만개의레시피]  요리,간단  764      5692

In [380]:
data1 =pd.read_excel('./data/통합본db용2.xlsx')

In [387]:
cook

번호  list  user_id
0   4     0  dptmf35
1   7     0  dptmf35
2   5     0  dptmf35
3   6     0  dptmf35

In [386]:
cook = pd.merge(cook,data1,on='번호')[['번호','list']]
cook['user_id'] = 'dptmf35'
cook.to_excel('cook.xlsx')

In [378]:
cook = get_recommend_media(data, title='세상 간단한 라면 요리 10가지')
cook['list']=0
cook[['번호','재생시간','list']]
cook.to_excel('cook.xlsx')

KeyError: "['번호'] not in index"

In [306]:
cos_sim2 = cosine_similarity(c_vec_cat, c_vec_cat).argsort()[:,::-1]

In [307]:
#런타임 고려
def get_recommend_media2(df, title, top=5) :
    indexlist = data['재생시간'].index
    
    target_media_index = df[df['제목']==title].index.values
    
    print(target_media_index)
    
    simm_index = cos_sim2[target_media_index,:top].reshape(-1)
    
    simm_index = [i for i in simm_index if abs(df['재생시간'][target_media_index]-df['재생시간'][indexlist[i]<20])]
    print(simm_index)
    
    simm_index = simm_index[simm_index != target_media_index[0]]
    
    result = df.iloc[simm_index].sort_values('조회수',ascending = False)[:10]
    
    return result

In [308]:
data[data['제목']=='세상 간단한 라면 요리 10가지'].index.values

array([1], dtype=int64)

In [309]:
get_recommend_media2(data, title='세상 간단한 라면 요리 10가지')

[1]


KeyError: True

# SVD

In [310]:
rating_data = pd.read_excel('./data/mydata.xlsx')
media_data =pd.read_excel('./data/통합본db용2.xlsx')

In [311]:
rating_data.head()

user_id  media_id preference job gender  age  rate
0        1         1         요리  학생      여   20    10
1        1         2         요리  학생      여   20     9
2        1         3         요리  학생      여   20     9
3        1         4         요리  학생      여   20     8
4        1         5         요리  학생      여   20     9

In [313]:
rating_data = rating_data[['user_id','media_id','rate']]

In [315]:
media_data = media_data[['번호','제목']]

In [317]:
media_data.columns = ['media_id', 'title']

In [318]:
user_media = pd.merge(rating_data,media_data,on='media_id')
user_media.head()

user_id  media_id  rate                                          title
0        1         1    10                              세상 간단한 라면 요리 10가지
1        6         1     2                              세상 간단한 라면 요리 10가지
2        8         1     4                              세상 간단한 라면 요리 10가지
3        1         2     9  ***간단요리 신전 떡볶이 만들기//똑같음주의//분식집 갈필요없는 자취요리 레시피
4        6         2     1  ***간단요리 신전 떡볶이 만들기//똑같음주의//분식집 갈필요없는 자취요리 레시피

In [320]:
user_media_rating = user_media.pivot_table('rate', index='user_id', columns='title').fillna(0)

In [321]:
user_media_rating.head()

title    ***간단요리 신전 떡볶이 만들기//똑같음주의//분식집 갈필요없는 자취요리 레시피  \
user_id                                                  
1                                                  9.0   
2                                                  0.0   
3                                                  0.0   
4                                                  0.0   
5                                                  0.0   

title    //Sato collapsed a 50 story building - challenging Police Te  \
user_id                                                                 
1                                                      0.0              
2                                                      0.0              
3                                                      0.0              
4                                                      0.0              
5                                                      3.0              

title    1분 1초도 놓칠 수 없는 아기고양이의 귀여운 행동  1분 시리얼 토스트 ! 1분이면 끝! [만개의레시피]  \
user_id                                                                
1                                 0.0                            0.0   
2                                 0.0                            0.0   
3                                 0.0                            0.0   
4                                 8.0                            0.0   
5                                 0.0                            0.0   

title    1분 일본어 _'일단' 일본어 배우기  3일만에 주인만난 강아지😳기절직전  4분예고「공각기동대ARISE」  \
user_id                                                               
1                         0.0                 0.0               0.0   
2                         0.0                 0.0               0.0   
3                         0.0                 3.0               0.0   
4                         5.0                10.0               0.0   
5                         0.0                 0.0               4.0   

title    Ava Max - So  I [Official Music Video]  \
user_id                                           
1                                           0.0   
2                                           0.0   
3                                           0.0   
4                                           0.0   
5                                           9.0   

title    BLACKPINK - 'Ice Cre (with Selena Gomez)' M/V  \
user_id                                                  
1                                                  0.0   
2                                                  0.0   
3                                                  0.0   
4                                                  0.0   
5                                                  0.0   

title    Coldplay - Paradise (Official Video)  ...  \
user_id                                        ...   
1                                         0.0  ...   
2                                         0.0  ...   
3                                         0.0  ...   
4                                         0.0  ...   
5                                         0.0  ...   

title    왕자 치즈감자 - 대만 스린야시장 길거리음식 / Prince Cheese Potato - Taiwan street food  \
user_id                                                                         
1                                                      0.0                      
2                                                      0.0                      
3                                                      0.0                      
4                                                      0.0                      
5                                                      0.0                      

title    일본어 초보라면 〇〇가 가장 중요합니다. 한자는 그 다음이죠.  \
user_id                                       
1                                       0.0   
2                                       8.0   
3                                       0.0   
4                                       6.0   
5                                       0.0   

title    일본여행에서 당장 써먹을 수 있는 3분 일본어회화

In [322]:
user_media_rating = user_media_rating.values.T

In [330]:
user_media_rating

array([[ 9. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  3. ,  9. ,  0. ,  0. ,  0. ,  0. ,  8. ,
         0. ,  0. ],
       [ 0. ,  0. ,  0. ,  8. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  7. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ],
       [ 0. ,  0. ,  0. ,  5. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ],
       [ 0. ,  0. ,  3. , 10. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  9. ],
       [ 0. ,  0. ,  0. ,  0. ,  4. ,  0. ,  0. ,  0. ,  0. ,  0. ,  7. ,
         0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  9. ,  0. ,  0. ,  3. ,  0. ,  0. ,  0. ,
         0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  8. ,  0. ,  0. ,  0. ,
         0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  4. ,  0. ,  0. ,  0. ,
         0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. , 

In [324]:
from sklearn.decomposition import TruncatedSVD
SVD = TruncatedSVD(n_components=5)

In [325]:
matrix = SVD.fit_transform(user_media_rating)
matrix.shape

(57, 5)

In [327]:
corr = np.corrcoef(matrix)
corr.shape

(57, 57)

In [329]:
user_media_rating

array([[ 9. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  3. ,  9. ,  0. ,  0. ,  0. ,  0. ,  8. ,
         0. ,  0. ],
       [ 0. ,  0. ,  0. ,  8. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  7. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ],
       [ 0. ,  0. ,  0. ,  5. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ],
       [ 0. ,  0. ,  3. , 10. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  9. ],
       [ 0. ,  0. ,  0. ,  0. ,  4. ,  0. ,  0. ,  0. ,  0. ,  0. ,  7. ,
         0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  9. ,  0. ,  0. ,  3. ,  0. ,  0. ,  0. ,
         0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  8. ,  0. ,  0. ,  0. ,
         0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  4. ,  0. ,  0. ,  0. ,
         0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. , 

In [331]:
user_media_rating1 = user_media.pivot_table('rate', index='user_id', columns='title').fillna(0)

In [332]:
media_title = user_media_rating1.columns
media_title_list = list(media_title)

In [336]:
coffey_hands = media_title_list.index('1분 1초도 놓칠 수 없는 아기고양이의 귀여운 행동')
print(coffey_hands)

2


In [337]:
corr_coffey_hands = corr[coffey_hands]
list(media_title[(corr_coffey_hands >=0.9)])[:10]

['1분 1초도 놓칠 수 없는 아기고양이의 귀여운 행동',
 "1분 일본어 _'일단' 일본어 배우기",
 '3일만에 주인만난 강아지😳기절직전',
 '새로 태어난 동생을 너무나 사랑하는 강아지',
 '얼음 속 잉어를 노리는 고양이',
 '자꾸 우리집으로 퇴근하는 고양이 ㅣ Surprising Reason Why This Cat Keeps Coming Back To My House Every Night?!',
 '저절로 웃음 지어지는 1분 아기쩡이 영상 [반려동물 강아지 쩡이 영상]']

In [341]:
pre_list = list(media_title[(corr_coffey_hands >=0.9)])[:10]

In [338]:
import time
time.time()

1600913302.727055

In [339]:
time.time()

1600913312.8352587

In [340]:
import matplotlib.pyplot as plt
import seaborn as sns
import cx_Oracle
import os
os.putenv('NLS_LANG','KOREAN_KOREA.KO16MSWIN949')
conn = cx_Oracle.connect('jokp','1234','localhost/XE')
df_media = pd.read_sql("select * from media order by media_id",con=conn, index_col = 'MEDIA_ID')
df_media.head()

TITLE  \
MEDIA_ID                                                      
1                                         세상 간단한 라면 요리 10가지   
10        오산 오색야시장 │ 냉면 구이 │ Kao Leng Mian │ 한국 길거리 음식 │...   
11        대학로 아이스크림 와플 - 한국 길거리음식 / Waffle with Ice Crea...   
12                   1500원 시장표 김밥의 놀라운 퀄리티 / 길거리음식 / 안양중앙시장   
13        왕자 치즈감자 - 대만 스린야시장 길거리음식 / Prince Cheese Potat...   

                    CHANNEL    UP  DOWN    VIEWS RUNNING_TIME      DATES  \
MEDIA_ID                                                                   
1                      승우아빠  9476   163   612478        10:29 2020-02-07   
10              Mukkebi 먹깨비  4346   825  1209848        04:13 2019-05-12   
11                김김푸드KFood  7860   238   910031        03:01 2020-04-09   
12        푸드킹덤 Food Kingdom  3981   226   788348        05:28 2019-10-10   
13               Soon Films    49     3     4334        01:04 2018-06-09   

                                 HASHTAG  \
MEDIA_ID                                   
1         #라면요리 #승우아빠 #남편세끼 #세상간단한 #라면스프   
10                 #오산 #야시장 #냉면구이 #길거리음식   
11                    #Waffle #와플 #대학로와플   
12                  #시장김밥 #길거리음식 #안양중앙시장   
13                      #치즈감자 #대만 #스린야시장   

                                                URL  \
MEDIA_ID                                              
1         https://www.youtube.com/embed/NrRJ-osLP4c   
10        https://www.youtube.com/embed/rKFN9UIzXVk   
11        https://www.youtube.com/embed/3G0g9XT0QYw   
12        https://www.youtube.com/embed/2TmiaDywGsE   
13        https://www.youtube.com/embed/kPZfHwoGpPs   

                                                 THUMNNAILS  CATEGORY  
MEDIA_ID                                                               
1         https://i.ytimg.com/vi/NrRJ-osLP4c/hqdefault.j...  요리, 간단요리  
10        https://i.ytimg.com/vi/rKFN9UIzXVk/hqdefault.j...    요리,길거리  
11        https://i.ytimg.com/vi/3G0g9XT0QYw/hqdefault.j...   요리, 길거리  
12        https://i.ytimg.com/vi/2TmiaDywGsE/hqdefault.j...   요리, 길거리  
13        https://i.ytimg.com/vi/kPZfHwoGpPs/hqdefault.j...   요리, 길거리

In [353]:
prelist = pd.DataFrame(pre_list)
prelist.columns = ['title']
prelist.head()

title
0  1분 1초도 놓칠 수 없는 아기고양이의 귀여운 행동
1          1분 일본어 _'일단' 일본어 배우기
2            3일만에 주인만난 강아지😳기절직전
3       새로 태어난 동생을 너무나 사랑하는 강아지
4              얼음 속 잉어를 노리는 고양이

In [366]:
store = pd.merge(prelist,media_data,on='title')

In [367]:
store['user_id'] = 'dptmf35'

In [368]:
store.head()

title  media_id  user_id
0  1분 1초도 놓칠 수 없는 아기고양이의 귀여운 행동        39  dptmf35
1          1분 일본어 _'일단' 일본어 배우기        56  dptmf35
2            3일만에 주인만난 강아지😳기절직전        45  dptmf35
3       새로 태어난 동생을 너무나 사랑하는 강아지        48  dptmf35
4              얼음 속 잉어를 노리는 고양이        42  dptmf35

In [369]:
pre_list[2]

'3일만에 주인만난 강아지😳기절직전'

In [373]:
store = store[['media_id','user_id']]

In [ ]:
store['']

In [375]:
store.to_excel('store.xlsx')

In [376]:
store

media_id  user_id
0        39  dptmf35
1        56  dptmf35
2        45  dptmf35
3        48  dptmf35
4        42  dptmf35
5        40  dptmf35
6        44  dptmf35

In [3]:
import surprise

In [4]:
import numpy as np

In [87]:
data1 = surprise.Dataset.load_builtin('ml-100k')
type(data1)

surprise.dataset.DatasetAutoFolds

In [88]:
data1.raw_ratings

[('196', '242', 3.0, '881250949'),
 ('186', '302', 3.0, '891717742'),
 ('22', '377', 1.0, '878887116'),
 ('244', '51', 2.0, '880606923'),
 ('166', '346', 1.0, '886397596'),
 ('298', '474', 4.0, '884182806'),
 ('115', '265', 2.0, '881171488'),
 ('253', '465', 5.0, '891628467'),
 ('305', '451', 3.0, '886324817'),
 ('6', '86', 3.0, '883603013'),
 ('62', '257', 2.0, '879372434'),
 ('286', '1014', 5.0, '879781125'),
 ('200', '222', 5.0, '876042340'),
 ('210', '40', 3.0, '891035994'),
 ('224', '29', 3.0, '888104457'),
 ('303', '785', 3.0, '879485318'),
 ('122', '387', 5.0, '879270459'),
 ('194', '274', 2.0, '879539794'),
 ('291', '1042', 4.0, '874834944'),
 ('234', '1184', 2.0, '892079237'),
 ('119', '392', 4.0, '886176814'),
 ('167', '486', 4.0, '892738452'),
 ('299', '144', 4.0, '877881320'),
 ('291', '118', 2.0, '874833878'),
 ('308', '1', 4.0, '887736532'),
 ('95', '546', 2.0, '879196566'),
 ('38', '95', 5.0, '892430094'),
 ('102', '768', 2.0, '883748450'),
 ('63', '277', 4.0, '875747401

In [22]:
from surprise.model_selection import KFold

options = {
    'method' : 'als',
    'n_epochs' : 5,
    'reg_u' : 12,
    'reg_i' : 5
}

algo = surprise.BaselineOnly(options)

np.random.seed(0)
acc = np.zeros(3)
cv = KFold(3)

for i, (trainset, testset) in enumerate(cv.split(data)) : 
    algo.fit(trainset)
    predictions = algo.test(testset)
    acc[i] = surprise.accuracy.rmse(predictions, verbose=True)

acc.mean()

AttributeError: 'numpy.ndarray' object has no attribute 'raw_ratings'

In [20]:
from surprise.model_selection import cross_validate

cross_validate(algo,data)

AttributeError: 'numpy.ndarray' object has no attribute 'raw_ratings'

In [ ]:
#COSINE

sim_options = {'name' : 'cosine'}
algo = surprise.KNNBasic(sim_options=sim_options)
cross_validate(algo,data)['test_mae'].mean()

In [ ]:
#PEARSON

sim_options = {'name' : 'pearson'}
algo = surprise.KNNBasic(sim_options=sim_options)
cross_validate(algo,data)['test_mae'].mean()

In [ ]:
#PEARSON_BASELINE

sim_options = {'name': 'pearson_baseline'}
algo = surprise.KNNBasic(sim_options=sim_options)
cross_validate(algo, data)["test_mae"].mean()

In [ ]:
#KNN Bbaseline

sim_options = {'name': 'pearson_baseline'}
algo = surprise.KNNWithMeans(sim_options=sim_options)
cross_validate(algo, data)["test_mae"].mean()

In [ ]:
#SVD

%%time
algo = surprise.SVD(n_factors=100)
cross_validate(algo, data)["test_mae"].mean()

In [ ]:
#NMF

%%time
algo = surprise.NMF(n_factors=100)
cross_validate(algo, data)["test_mae"].mean()